package com.clockweather.app.util

import android.annotation.SuppressLint
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import com.clockweather.app.receiver.LocationUpdatesReceiver
import com.clockweather.app.worker.WeatherRefreshLocationResolver
import com.google.android.gms.location.FusedLocationProviderClient
import com.google.android.gms.location.LocationRequest
import com.google.android.gms.location.LocationServices
import com.google.android.gms.location.Priority
import java.util.concurrent.TimeUnit

/**
 * Manages passive location updates from Google Play Services.
 *
 * Uses [Priority.PRIORITY_PASSIVE] with a 5 km displacement filter matching the
 * weather relocation threshold. This consumes 0% extra battery because it never
 * turns on the GPS radio on its own — it simply harvests fixes generated by other
 * foreground apps (e.g. Twitter, Maps).
 */
object PassiveLocationManager {

    private const val TAG = "PassiveLocationManager"
    private const val REQUEST_CODE = 4001
    private const val PASSIVE_INTERVAL_MINUTES = 15L
    private const val MIN_UPDATE_INTERVAL_MINUTES = 5L

    fun getPendingIntent(context: Context): PendingIntent {
        val intent = Intent(context, LocationUpdatesReceiver::class.java).apply {
            action = LocationUpdatesReceiver.ACTION_LOCATION_UPDATE
        }
        val flags = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_MUTABLE
        } else {
            PendingIntent.FLAG_UPDATE_CURRENT
        }
        return PendingIntent.getBroadcast(context, REQUEST_CODE, intent, flags)
    }

    @SuppressLint("MissingPermission")
    fun register(
        context: Context,
        fusedLocationClient: FusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(context),
    ) {
        // Passive delivery to a background receiver is still gated by the "all the
        // time" grant on Android 10+ — PRIORITY_PASSIVE only means "don't power on
        // GPS for me", not "deliver to me while backgrounded". Registering without
        // it reports success and then never fires. isBackgroundGranted is always
        // true below Android 10, where the foreground grant already covers this.
        if (!BackgroundLocationAccess.isForegroundGranted(context) ||
            !BackgroundLocationAccess.isBackgroundGranted(context)
        ) {
            Log.d(TAG, "Location not granted for background delivery; skipping passive registration")
            return
        }

        try {
            val request = LocationRequest.Builder(
                Priority.PRIORITY_PASSIVE,
                TimeUnit.MINUTES.toMillis(PASSIVE_INTERVAL_MINUTES)
            )
                .setMinUpdateDistanceMeters(WeatherRefreshLocationResolver.SIGNIFICANT_MOVE_METERS.toFloat())
                .setMinUpdateIntervalMillis(TimeUnit.MINUTES.toMillis(MIN_UPDATE_INTERVAL_MINUTES))
                .build()

            val pendingIntent = getPendingIntent(context)
            fusedLocationClient.requestLocationUpdates(request, pendingIntent)
            Log.d(TAG, "Passive location updates registered successfully")
        } catch (e: SecurityException) {
            Log.w(TAG, "SecurityException registering passive location updates", e)
        } catch (e: Throwable) {
            Log.w(TAG, "Failed to register passive location updates", e)
        }
    }

    fun unregister(
        context: Context,
        fusedLocationClient: FusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(context),
    ) {
        try {
            val pendingIntent = getPendingIntent(context)
            fusedLocationClient.removeLocationUpdates(pendingIntent)
            Log.d(TAG, "Passive location updates unregistered successfully")
        } catch (e: SecurityException) {
            Log.w(TAG, "SecurityException unregistering passive location updates", e)
        } catch (e: Throwable) {
            Log.w(TAG, "Failed to unregister passive location updates", e)
        }
    }
}
